language: java
jdk: openjdk8

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

install:
  - ./gradlew assemble
  - ./gradlew -p keycloak-provider shadowJar

before_script:
  - chmod +x gradlew

script:
  - ./gradlew check
  - ./gradlew codeCoverageReport

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin

  #TAG
  - export TAG=$(if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi)

  # Frontend
  - export FRONTEND=galleog/piggymetrics-frontend
  - docker build -t $FRONTEND:$COMMIT ./pgm-frontend
  - docker tag $FRONTEND:$COMMIT $FRONTEND:$TAG
  - docker push $FRONTEND

  # API Gateway
  - export API_GATEWAY=galleog/piggymetrics-api-gateway
  - ./gradlew -p api-gateway jibDockerBuild --image=$API_GATEWAY -Djib.to.tags=$COMMIT
  - docker tag $API_GATEWAY:$COMMIT $API_GATEWAY:$TAG
  - docker push $API_GATEWAY

  # Account Service
  - export ACCOUNT_SERVICE=galleog/piggymetrics-account-service
  - ./gradlew -p account-service jibDockerBuild --image=$ACCOUNT_SERVICE -Djib.to.tags=$COMMIT
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # Statistics Service
  - export STATISTICS_SERVICE=galleog/piggymetrics-statistics-service
  - ./gradlew -p statistics-service jibDockerBuild --image=$ACCOUNT_SERVICE -Djib.to.tags=$COMMIT
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # Notification Service
  - export NOTIFICATION_SERVICE=galleog/piggymetrics-notification-service
  - ./gradlew -p notification-service jibDockerBuild --image=$ACCOUNT_SERVICE -Djib.to.tags=$COMMIT
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # Keycloak Provider
  - export KEYCLOAK_PROVIDER=galleog/piggymetrics-keycloak-provider
  - docker build -t $KEYCLOAK_PROVIDER:$COMMIT ./keycloak-provider
  - docker tag $KEYCLOAK_PROVIDER:$COMMIT $KEYCLOAK_PROVIDER:$TAG
  - docker push $KEYCLOAK_PROVIDER